### ISSUE TITLE
Support affinity in the deployment

### ISSUE THREAD

**Issue by roderik** [replicatedhq/replicated-sdk#164]
For precise placement in a locked down production nodepool we use the following

```
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: production
              operator: In
              values:
                - "true"
    tolerations:
      - effect: NoSchedule
        key: production
        operator: Equal
        value: "true"
```

I can set the tolerations but not the affinity
